# Challenge 2

In this challenge we will continue working with the `Pokemon` dataset. We will attempt solving a slightly more complex problem in which we will practice the iterative data analysis process you leaned in [this video](https://www.youtube.com/watch?v=xOomNicqbkk).

The problem statement is as follows:

**You are at a Pokemon black market planning to buy a Pokemon for battle. All Pokemon are sold at the same price and you can only afford to buy one. You cannot choose which specific Pokemon to buy. However, you can specify the type of the Pokemon - one type that exists in either `Type 1` or `Type 2`. Which type should you choose in order to maximize your chance of receiving a good Pokemon?**

To remind you about the 3 steps of iterative data analysis, they are:

1. Setting Expectations
1. Collecting Information
1. Reacting to Data / Revising Expectations

Following the iterative process, we'll guide you in completing the challenge.


## Problem Solving Iteration 1

In this iteration we'll analyze the problem and identify the breakthrough. The original question statement is kind of vague because we don't know what a *good pokemon* really means as represented in the data. We'll start by understanding the dataset and see if we can find some insights.

In [1]:
# Import libraries
import numpy as np
import pandas as pd

In [9]:
# Importing the dataset
pokemon = pd.read_csv('Pokemon.csv')
pokemon.head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False

From the data it seems whether a pokemon is good depends on its abilities as represented in the fields of `HP`, `Attack`, `Defense`, `Sp. Atk`, `Sp. Def`, `Speed`, and `Total`. We are not sure about `Generation` and `Legendary` because they are not necessarily the decisive factors of the pokemon abilities.

But `HP`, `Attack`, `Defense`, `Sp. Atk`, `Sp. Def`, `Speed`, and `Total` are a lot of fields! If we look at them all at once it's very complicated. This isn't Mission Impossible but it's ideal that we tackle this kind of problem after we learn Machine Learning (which you will do in Module 3). For now, is there a way to consolidate the fields we need to look into?

Fortunately there seems to be a way. It appears the `Total` field is computed based on the other 6 fields. But we need to prove our theory. If we can approve there is a formula to compute `Total` based on the other 6 abilities, we only need to look into `Total`.

We have the following expectation now:

#### The `Total` field is computed based on `HP`, `Attack`, `Defense`, `Sp. Atk`, `Sp. Def`, and `Speed`.

We need to collect the following information:

* **What is the formula to compute `Total`?**
* **Does the formula work for all pokemon?**

In the cell below, make a hypothesis on how `Total` is computed and test your hypothesis.

In [11]:
# your code here
pokemon_df = pd.read_csv('Pokemon.csv')

# Calculate Total based on the formula
pokemon_df['Calculated Total'] = (
    pokemon_df['HP'] +
    pokemon_df['Attack'] +
    pokemon_df['Defense'] +
    pokemon_df['Sp. Atk'] +
    pokemon_df['Sp. Def'] +
    pokemon_df['Speed']
)

# Compare the calculated Total with the provided Total
pokemon_df['Confirmed'] = pokemon_df['Total'] == pokemon_df['Calculated Total']

# Display the DataFrame with the results
print(pokemon_df[['Name', 'Total', 'Calculated Total', 'Confirmed']])
#The Hypothesis is CONFIRMED!!! YAY!

                      Name  Total  Calculated Total  Confirmed
0                Bulbasaur    318               318       True
1                  Ivysaur    405               405       True
2                 Venusaur    525               525       True
3    VenusaurMega Venusaur    625               625       True
4               Charmander    309               309       True
..                     ...    ...               ...        ...
795                Diancie    600               600       True
796    DiancieMega Diancie    700               700       True
797    HoopaHoopa Confined    600               600       True
798     HoopaHoopa Unbound    680               680       True
799              Volcanion    600               600       True

[800 rows x 4 columns]

## Problem Solving Iteration 2

Now that we have consolidated the abilities fields, we can update the problem statement. The new problem statement is:

### Which pokemon type is most likely to have the highest `Total` value?

In the updated problem statement, we assume there is a certain relationship between the `Total` and the pokemon type. But we have two *type* fields (`Type 1` and `Type 2`) that have string values. In data analysis, string fields have to be transformed to numerical format in order to be analyzed.

In addition, keep in mind that `Type 1` always has a value but `Type 2` is sometimes empty (having the `NaN` value). Also, the pokemon type we choose may be either in `Type 1` or `Type 2`.

Now our expectation is:

#### `Type 1` and `Type 2` string variables need to be converted to numerical variables in order to identify the relationship between `Total` and the pokemon type.

The information we need to collect is:

#### How to convert two string variables to numerical?

Let's address the first question first. You can use a method called **One Hot Encoding** which is frequently used in machine learning to encode categorical string variables to numerical. The idea is to gather all the possible string values in a categorical field and create a numerical field for each unique string value. Each of those numerical fields uses `1` and `0` to indicate whether the data record has the corresponding categorical value. A detailed explanation of One Hot Encoding can be found in [this article](https://hackernoon.com/what-is-one-hot-encoding-why-and-when-do-you-have-to-use-it-e3c6186d008f). You will formally learn it in Module 3.

For instance, if a pokemon has `Type 1` as `Poison` and `Type 2` as `Fire`, then its `Poison` and `Fire` fields are `1` whereas all other fields are `0`. If a pokemon has `Type 1` as `Water` and `Type 2` as `NaN`, then its `Water` field is `1` whereas all other fields are `0`.

#### In the next cell, use One Hot Encoding to encode `Type 1` and `Type 2`. Use the pokemon type values as the names of the numerical fields you create.

The new numerical variables you create should look like below:

![One Hot Encoding](../images/one-hot-encoding.png)

In [12]:
# your code here
type_1_encoded = pd.get_dummies(pokemon_df['Type 1'], prefix='Type1')
type_2_encoded = pd.get_dummies(pokemon_df['Type 2'], prefix='Type2')

# Combine encoded features with the original DataFrame
pokemon_encoded_df = pd.concat([pokemon_df, type_1_encoded, type_2_encoded], axis=1)

# Drop the original Type 1 and Type 2 columns
pokemon_encoded_df.drop(columns=['Type 1', 'Type 2'], inplace=True)

# Display the resulting DataFrame
print(pokemon_encoded_df.head())

   #                   Name  Total  HP  Attack  Defense  Sp. Atk  Sp. Def  \
0  1              Bulbasaur    318  45      49       49       65       65
1  2                Ivysaur    405  60      62       63       80       80
2  3               Venusaur    525  80      82       83      100      100
3  3  VenusaurMega Venusaur    625  80     100      123      122      120
4  4             Charmander    309  39      52       43       60       50

   Speed  Generation  ...  Type2_Ghost  Type2_Grass  Type2_Ground  Type2_Ice  \
0     45           1  ...        False        False         False      False
1     60           1  ...        False        False         False      False
2     80           1  ...        False        False         False      False
3     80           1  ...        False        False         False      False
4     65           1  ...        False        False         False      False

   Type2_Normal  Type2_Poison  Type2_Psychic  Type2_Rock  Type2_Steel  \
0         False          True          False       False        False
1         False          True          False       False        False
2         False          True          False       False        False
3         False          True          False       False        False
4         False         False          False       False        False

   Type2_Water
0        False
1        False
2        False
3        False
4        False

[5 rows x 49 columns]

## Problem Solving Iteration 3

Now we have encoded the pokemon types, we will identify the relationship between `Total` and the encoded fields. Our expectation is:

#### There are relationships between `Total` and the encoded pokemon type variables and we need to identify the correlations.

The information we need to collect is:

#### How to identify the relationship between `Total` and the encoded pokemon type fields?

There are multiple ways to answer this question. The easiest way is to use correlation. In the cell below, calculate the correlation of `Total` to each of the encoded fields. Rank the correlations and identify the #1 pokemon type that is most likely to have the highest `Total`.

In [26]:
# Calculate correlation of Total with encoded Type 1 and Type 2 fields
type_correlations = pokemon_encoded_df[pokemon_encoded_df.columns[pokemon_encoded_df.columns.str.startswith(('Type1', 'Type2'))]].corrwith(pokemon_encoded_df['Total'])

# Sort correlations in descending order
sorted_type_correlations = type_correlations.sort_values(ascending=False)

print("Correlations with Total:")
print(sorted_type_correlations)

Correlations with Total:
Type1_Dragon      0.196532
Type2_Fighting    0.138726
Type2_Dragon      0.115240
Type2_Ice         0.100870
Type1_Psychic     0.094364
Type1_Steel       0.082000
Type2_Psychic     0.076054
Type2_Fire        0.073234
Type2_Steel       0.070307
Type2_Dark        0.065844
Type2_Flying      0.054048
Type1_Fire        0.050527
Type1_Rock        0.037524
Type1_Flying      0.029504
Type1_Dark        0.017818
Type1_Electric    0.016715
Type2_Ground      0.016486
Type2_Electric    0.014669
Type1_Ghost       0.007594
Type1_Ground      0.004082
Type2_Rock       -0.000512
Type1_Ice        -0.002412
Type2_Ghost      -0.004885
Type2_Normal     -0.013956
Type1_Water      -0.015640
Type2_Water      -0.018800
Type2_Bug        -0.021375
Type2_Fairy      -0.024606
Type1_Fairy      -0.026948
Type1_Fighting   -0.029086
Type1_Grass      -0.036057
Type2_Grass      -0.039224
Type1_Poison     -0.057123
Type2_Poison     -0.067837
Type1_Normal     -0.104150
Type1_Bug        -0.143957
dtype: float64

# Bonus Question

Say now you can choose both `Type 1` and `Type 2` of the pokemon. In order to receive the best pokemon, which types will you choose?

In [27]:
# your code here
print("\n#1 Pokemon Type with the Highest Total:")
print(sorted_type_correlations.index[0])  # Index 0 corresponds to the highest correlation

#1 Pokemon Type with the Highest Total:
Type1_Dragon